# Generated by Django 4.1.6 on 2023-05-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="followed_by", to="main.person"
            ),
        ),
    ]
